version: '3.9'

services:
  web:
    # build: .
    image: yugyeong/piboo:v5.0.0
    container_name: django_app
    expose:
      - 8000
    env_file:
      - .env
    volumes:
      - static_data:/app/staticfiles
    restart: on-failure
  
  nginx: 
    image: nginx:latest
    container_name: nginx_proxy 
    ports:
      - "80:80" 
    volumes:
      - static_data:/app/staticfiles:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on: 
      - web
    restart: always

volumes:
  static_data: