# Generated by Django 5.2.2 on 2025-06-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="이메일",
            ),
        ),
    ]
