# Generated by Django 5.2.2 on 2025-06-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="age",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="나이"),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.IntegerField(
                blank=True, choices=[(0, "남자"), (1, "여자")], null=True, verbose_name="성별"
            ),
        ),
    ]
