# Generated by Django 4.2.22 on 2025-06-09 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_email"),
        ("users", "0004_chathistory"),
    ]

    operations = []
